### ISSUE TITLE
Appending to already installed seiscomp3

### ISSUE THREAD

**Issue by geolwangui** [swiss-seismological-service/scrtdd#36]
Hello,

I would like help in merging this add-on on already installed seiscomp3.

I have tried to follow the steps given but each time when in the make command I get two errors.

**Comment by luca-s** [comment]
Could you copy paste here the errors you see in the console? 

Also, what seiscomp version (tag or branch) are you compiling? 

What OS do you use?l

**Comment by geolwangui** [comment]
I'm using Ubuntu 16.04 and I was compiling the Jakarta 2018.327.06 version.

I will copy the errors when I try to install again in the meantime I have done the whole process in a new user and it has worked.

Now on using the add-on, I have seismic origins in a .xml file that I obtained from processing in seiscomp3 in the offline mode. How do I get to obtain the catalogue files and the rest and eventually relocate the seismic events?

**Comment by luca-s** [comment]
Currently you can use .xml files for single-event relocation only but it is not possible to use .xml files to generate the background catalog. The origins must be in the database to generate a background catalog. Then you can relocate new events one a time (single-event mode) via .xml files.

**Comment by geolwangui** [comment]
when I populate the events in the database then will it be okay without having the data in the archive?
How do I get the seiscomp ID? Can I use the event Id?

**Comment by luca-s** [comment]
> when I populate the events in the database then will it be okay without having the data in the archive?

Yes, you can choose to have the events in the database or not. Since you don't want them, I would suggest to dump the  events to flat files now so that you won't need them in the database anymore.

To dump your events to files, please follow the section "1.1 Dumping the candidate events to files".  Basically you just need to run one command:

`scrtdd --dump-catalog myCatalog.csv --verbosity=3 --console=1 [db options]`

>  How do I get the seiscomp ID? Can I use the event Id?

Yes, but if you like to use the event Id then you need specify what origin to use for each event (e.g. the preferred origin). This means you need to add an option to the previous command (again see section "1.1 Dumping the candidate events to files"):

`scrtdd --dump-catalog myCatalog.csv --dump-catalog-options 'preferred,any,any,none,any --verbosity=3 --console=1 [db options]`

```
--dump-catalog-options  format is 'type,evalmode,includeCreator,excludeCreator,region'
  type = preferred | last | first  
  evalmode = any | onlyManual | onlyAutomatic  
  includeCreator = any | author | methodID  
  excludeCreator = none | author | methodID  
  region = any | profileName
```

**Comment by geolwangui** [comment]
Ive been able to generate the events.csv, phase.csv and station.csv file and followed the guidelines on setting up the configuration to relocate.

I am getting this on my terminal and no relocation files
~$ scrtdd --reloc-profile myprofile --verbosity=3 --console=1 -d mysql://maggie:maggie@localhost/seiscomp3 
17:12:08 [info] Plugin dbmysql registered
17:12:08 [info] 
Plugins:
--------
 [1]
  description: MySQL database driver
       author: GFZ Potsdam <seiscomp-devel@gfz-potsdam.de>
      version: 0.9.2
          API: 12.0.0

17:12:08 [info] Connect to database
17:12:08 [info] Read database service parameters from configfile
17:12:08 [info] Trying to connect to mysql://maggie:maggie@localhost/seiscomp3
17:12:08 [info] Connected successfully
17:12:08 [info] Loading complete inventory
17:12:08 [info] Finished loading complete inventory
17:12:08 [info] Loading configuration module
17:12:08 [info] Finished loading configuration module
17:12:08 [info] Disable timer
17:12:08 [info] Disconnecting from database

**Comment by luca-s** [comment]
It seems the code doesn't find the provile called "myprofile" so it doesn't do anything. Is it possible the profile name is myProfile or MyProfile?

I guess the scrtdd messages could be improved :)

**Comment by geolwangui** [comment]
It's "myprofile"
I have a velocity model for the area, how do I store it in seiscomp so that it can be used?

**Comment by luca-s** [comment]
> It's "myprofile"

scrtdd doesn't find that profile in the configuration otherwise you would see the relocation logs and the output.

>  I have a velocity model for the area, how do I store it in seiscomp so that it can be used?

This is a general seiscomp topic and you can use the seiscomp forum for clarification. For example here is a thread on the topic https://forum.seiscomp.de/t/custom-travel-time-table-creation-in-seiscomp/1873
Any velocity model added to seiscomp is available in scrtdd and you can select that in the "solver" options.

**Comment by geolwangui** [comment]
> Could you copy paste here the errors you see in the console?

 59%] Building CXX object src/trunk/plugins/database/mysql/CMakeFiles/dbmysql.dir/mysqldatabaseinterface.cpp.o
/home/seismics/sc3-src/src/trunk/plugins/database/mysql/mysqldatabaseinterface.cpp: In member function 'virtual bool Seiscomp::Database::MySQLDatabase::open()':
/home/seismics/sc3-src/src/trunk/plugins/database/mysql/mysqldatabaseinterface.cpp:79:2: error: 'my_bool' was not declared in this scope
  my_bool reconnect = true;
  ^
/home/seismics/sc3-src/src/trunk/plugins/database/mysql/mysqldatabaseinterface.cpp:80:60: error: ISO C++ forbids taking the address of an unqualified or parenthesized non-static member function to form a pointer to member function.  Say '&Seiscomp::Database::MySQLDatabase::reconnect' [-fpermissive]
  mysql_options(_handle, MYSQL_OPT_RECONNECT, (const char*)&reconnect);
                                                            ^
/home/seismics/sc3-src/src/trunk/plugins/database/mysql/mysqldatabaseinterface.cpp:80:60: error: invalid cast from type 'bool (Seiscomp::Database::MySQLDatabase::*)()' to type 'const char*'
/home/seismics/sc3-src/src/trunk/plugins/database/mysql/mysqldatabaseinterface.cpp:110:60: error: ISO C++ forbids taking the address of an unqualified or parenthesized non-static member function to form a pointer to member function.  Say '&Seiscomp::Database::MySQLDatabase::reconnect' [-fpermissive]
  mysql_options(_handle, MYSQL_OPT_RECONNECT, (const char*)&reconnect);
                                                            ^
/home/seismics/sc3-src/src/trunk/plugins/database/mysql/mysqldatabaseinterface.cpp:110:60: error: invalid cast from type 'bool (Seiscomp::Database::MySQLDatabase::*)()' to type 'const char*'
src/trunk/plugins/database/mysql/CMakeFiles/dbmysql.dir/build.make:62: recipe for target 'src/trunk/plugins/database/mysql/CMakeFiles/dbmysql.dir/mysqldatabaseinterface.cpp.o' failed
make[2]: *** [src/trunk/plugins/database/mysql/CMakeFiles/dbmysql.dir/mysqldatabaseinterface.cpp.o] Error 1
CMakeFiles/Makefile2:5841: recipe for target 'src/trunk/plugins/database/mysql/CMakeFiles/dbmysql.dir/all' failed
make[1]: *** [src/trunk/plugins/database/mysql/CMakeFiles/dbmysql.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 

This are the errors I am getting

**Comment by geolwangui** [comment]
when relocating since this is my first time doing so... I did not get cross correlation, could that be reason why the relocation did not work?
If so how should I set the cross correlation parameters?

**Comment by luca-s** [comment]
> This are the errors I am getting

Those errors are not scrtdd code related. It seems you have issues compiling seiscomp3 itself. I would suggest to use seiscomp forum for those kind of issues.

As a side note, after you cloned the seiscomp3 code, did you checked out a specific versiont tag or are you trying to compile the master branch (when I compile seiscomp3 from source code, I usually check out an official version, e.g. "git checkout release/jakarta/2018.327.23" so that I am sure I am using the code belonging to an official version that is tested)

**Comment by luca-s** [comment]
> when relocating since this is my first time doing so... I did not get cross correlation, could that be reason why the relocation did not work?

The first thing to check is that scrtdd can see the waveforms. Plase make sure you have properly configured the [recordStream](https://www.seiscomp.de/doc/apps/global_recordstream.html) parameter in the `global` settings. The rercordStream parameter instructs seiscomp modules on how to access waveforms data (e.g. fdsn, sds archive, etc)

> If so how should I set the cross correlation parameters?

There are default parameres that you can modifiy but if you don't get any cross-correlation result at all it is problably because of recorStream parameter.

**Comment by geolwangui** [comment]
> > It's "myprofile"
> 
> scrtdd doesn't find that profile in the configuration otherwise you would see the relocation logs and the output.

why is it that it cannot find the profile? I have created another profile and still it cannot be found.

I have updated the configuration on seiscomp3 but still nothing

**Comment by geolwangui** [comment]
I have been able to relocate the events and now I have the event, phase and station files, can I load the results back to seiscomp3 or that's the end?

**Comment by luca-s** [comment]
You can load back the files to seiscomp, but you do not need to. That's your choice. 

If you intent to relocate events in real-time (single event mode) you can use those files (the relocated ones) as backgound catalog for a real-time profile. Normally you might want to update your background catalog every now and then (e.g. 1 year) and then you simply need to replace the files. 

If you like to have your background catalog in seiscomp, you can convert the triplet files to xml format (e.g. `scrtdd --dump-catalog-xml reloc-station.csv,reloc-event.csv,reloc-phase.csv`). At this point you can use seiscomp commands to import the xml file in the database (e.g. [scdb](https://www.seiscomp.de/doc/apps/scdb.html) )

**Comment by luca-s** [comment]
One more thing that was not clear from my answer. For some users the real-time relocation is not important, they are only interested in the multi-event relocation to analyse the events cluster structure. In that case, once you get the relocated catalog (reloc-event.csv, reloc-phase.csv, reloc-station.csv) they simply load the files in their external software/scripts for further analysis and there is no more interaction with seiscomp. This is another way of making use of scrtdd.

**Comment by geolwangui** [comment]
I want to regenerate focal mechanisms in seiscomp3

when i run this command what's the name of the sc3xml file and where is it stored? I did run it but cannot locate the sc3xml file,,,

**Comment by luca-s** [comment]
The command print the catalog to the console, so you can redirect the output to a file like this:

`scrtdd --dump-catalog-xml reloc-station.csv,reloc-event.csv,reloc-phase.csv > mycat.xml`

**Comment by luca-s** [comment]
I am closing this now. Feel free to reopen it whether it is needed
