### ISSUE TITLE
supporting NLL lambert transformation 

### ISSUE THREAD

**Issue by filefolder** [swiss-seismological-service/scrtdd#50]
Hi, I was struggling to get this to work until I finally noticed that NonLinLoc models with TRANS LAMBERT are not supported for the NonLinLoc solver. Is this something that is difficult to incorporate? I would have guessed the NLL model parameters might be completely independent from the scrtdd code but I honestly have no idea. 

If this seems like a feature that won't ever happen, let me know, I will try to recreate my models as SIMPLE transformations, although I would prefer not to if possible :)

**Comment by luca-s** [comment]
It is not difficult to incorporate TRANS LAMBERT and the code is well designed to add that transformation too, but it requires some time. Since we do not use it I have no plans at the moment to add the feature.

However, if you are willing to provide a pull request for it, I would be very happy to guide you through the steps required to add the missing feature.

**Comment by filefolder** [comment]
Absolutely, sounds much more pleasant than recreating these models! Happy to have a go at it when I find a minute.

**Comment by luca-s** [comment]
Great! What is required is to add code that handles Lambert transformation in the [Transform class](https://github.com/swiss-seismological-service/scrtdd/blob/0d1e2d0d7926fa61887d0e5dcce10e4b4c8317f3/libs/hdd/nllttt.h#L37), then scrtdd will be able to use your grid files.
 
Basically you need to add some code to a few Transform class methods:

* [Transform::parse](https://github.com/swiss-seismological-service/scrtdd/blob/0d1e2d0d7926fa61887d0e5dcce10e4b4c8317f3/libs/hdd/nllttt.cpp#L957) receives the[ transform parameters](http://alomax.free.fr/nlloc/soft7.00/control.html#_generic_trans_) contained in the grid header and initializes the `Transform` class. For example the following header line will be received in input to `Transform::parse` as a vector of 12 string tokens.
```
TRANSFORM  LAMBERT RefEllipsoid Clarke-1880  LatOrig 43.750000  LongOrig 5.750000  FirstStdParal 43.199300  SecondStdParal 44.996100
```
Since we want the code to be perfectly compatible with NonLinLoc you can check what the [NLL code does](https://github.com/swiss-seismological-service/sed-SeisComP-contributions/blob/d5532b3c5d39abe0f725a77d0428f8f68c98158e/libs/3rd-party/nll/GridLib.c#L578).


* [Transform::fromLatLon](https://github.com/swiss-seismological-service/scrtdd/blob/0d1e2d0d7926fa61887d0e5dcce10e4b4c8317f3/libs/hdd/nllttt.cpp#L1021) and [Transform::toLatLon](https://github.com/swiss-seismological-service/scrtdd/blob/0d1e2d0d7926fa61887d0e5dcce10e4b4c8317f3/libs/hdd/nllttt.cpp#L1064). Again, simulate what NLL code does [here](https://github.com/swiss-seismological-service/sed-SeisComP-contributions/blob/d5532b3c5d39abe0f725a77d0428f8f68c98158e/libs/3rd-party/nll/GridLib.c#L3322) and [here](https://github.com/swiss-seismological-service/sed-SeisComP-contributions/blob/d5532b3c5d39abe0f725a77d0428f8f68c98158e/libs/3rd-party/nll/GridLib.c#L3397).


* [Transform::fromLatLonAngle](https://github.com/swiss-seismological-service/scrtdd/blob/0d1e2d0d7926fa61887d0e5dcce10e4b4c8317f3/libs/hdd/nllttt.cpp#L1107) and [Transform::toLatLonAngle](https://github.com/swiss-seismological-service/scrtdd/blob/0d1e2d0d7926fa61887d0e5dcce10e4b4c8317f3/libs/hdd/nllttt.cpp#L1129). The current code already handles Lambert, as long as `info.rot` is properly populated by `Transform::parse`. Also both methods need to extend [the](https://github.com/swiss-seismological-service/scrtdd/blob/0d1e2d0d7926fa61887d0e5dcce10e4b4c8317f3/libs/hdd/nllttt.cpp#L1109) [check](https://github.com/swiss-seismological-service/scrtdd/blob/0d1e2d0d7926fa61887d0e5dcce10e4b4c8317f3/libs/hdd/nllttt.cpp#L1131) on `info.type` to support `"LAMBERT"`.

Let me know if this makes sense or if you need more information to get started.

Thanks!

**Comment by luca-s** [comment]
I forgot one important point. You will notice that NLL code uses the lambert [conversion](https://github.com/swiss-seismological-service/sed-SeisComP-contributions/blob/d5532b3c5d39abe0f725a77d0428f8f68c98158e/libs/3rd-party/nll/map_project.c#L281) [functions](https://github.com/swiss-seismological-service/sed-SeisComP-contributions/blob/d5532b3c5d39abe0f725a77d0428f8f68c98158e/libs/3rd-party/nll/map_project.c#L254) defined in [map_project.c](https://github.com/swiss-seismological-service/sed-SeisComP-contributions/blob/master/libs/3rd-party/nll/map_project.c), which is code derived from `GMT`. Since `GMT` has an open and free license you can copy the code inside `scrtdd`, but please put it in  `scrtdd/libs/3rd-party/gmt`.

There is also one last issue. The `GMT` code uses global variables and I cannot accept. I need to ask you to remove the global variables and store any necessary information inside the `Transform` class instead.

**Comment by filefolder** [comment]
Just checking in, thanks for all that. At the moment I've had to just revert to a simple transformation to get a dataset done but I still to do this eventually. Although I am not a C person at all or even much of a programmer so it may take me a while

**Comment by luca-s** [comment]
The code is landing on master soon.
