### ISSUE TITLE
error: variable ‘std::ofstream os’ has initializer but incomplete type

### ISSUE THREAD

**Issue by morealaz** [swiss-seismological-service/scrtdd#64]
Hi, 
I got following errors when trying to compile seiscomp with scrtdd:
```
/home/sysop/sc_source/src/extras/scrtdd/libs/hdd/utils.cpp: In function ‘void HDD::writeXCorrToFile(const XCorrCache&, const Catalog&, const std::string&)’:
/home/sysop/sc_source/src/extras/scrtdd/libs/hdd/utils.cpp:291:19: error: variable ‘std::ofstream os’ has initializer but incomplete type
  291 |   ofstream os(file);
      |                   ^
/home/sysop/sc_source/src/extras/scrtdd/libs/hdd/utils.cpp: In lambda function:
/home/sysop/sc_source/src/extras/scrtdd/libs/hdd/utils.cpp:302:5: error: ‘os’ is not captured
  302 |     os << strf("%u,%u,%s,%s,%s,%s,%c,%s,%f,%f", ev1, ev2,
      |     ^~
/home/sysop/sc_source/src/extras/scrtdd/libs/hdd/utils.cpp:296:29: note: the lambda has no capture-default
  296 |   auto callback = [&os, &cat](unsigned ev1, unsigned ev2,
      |                             ^
/home/sysop/sc_source/src/extras/scrtdd/libs/hdd/utils.cpp:291:12: note: ‘<typeprefixerror>os’ declared here
  291 |   ofstream os(file);
      |            ^~
make[2]: *** [src/extras/scrtdd/libs/hdd/CMakeFiles/seiscomp_hdd.dir/build.make:146: src/extras/scrtdd/libs/hdd/CMakeFiles/seiscomp_hdd.dir/utils.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:10621: src/extras/scrtdd/libs/hdd/CMakeFiles/seiscomp_hdd.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

```
I use GCC 12.1.0 on Archlinux for compiling

**Comment by luca-s** [comment]
@morealaz you are chasing and squashing bugs on SED repos recently ;) Thanks.

Would you mind adding `#include <fstream>` at the top of `scrtdd/libs/hdd/utils.cpp` and see if it compiles fine? If so would you mind providing a PR with the fix?

**Comment by morealaz** [comment]
I added `#include <fstream>` at the top of `scrtdd/libs/hdd/utils.cpp` and `#include <string>` at the top of `scrtdd/libs/hdd/solver.h` file and got this error when compiling `solver.cpp`:

```
In file included from /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/solver.cpp:17:
/home/sysop/sc_source/src/extras/scrtdd/libs/hdd/solver.h:274:15: error: field ‘_type’ has incomplete type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’}
  274 |   std::string _type;
      |               ^~~~~
In file included from /usr/include/c++/12.1.0/iosfwd:39,
                 from /usr/include/c++/12.1.0/bits/shared_ptr.h:52,
                 from /usr/include/c++/12.1.0/memory:77,
                 from /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/solver.h:23:
/usr/include/c++/12.1.0/bits/stringfwd.h:72:11: note: declaration of ‘std::string’ {aka ‘class std::__cxx11::basic_string<char>’}
   72 |     class basic_string;
      |           ^~~~~~~~~~~~
/home/sysop/sc_source/src/extras/scrtdd/libs/hdd/solver.h:123:22: error: ‘type’ has incomplete type
  123 |   Solver(std::string type) : _type(type) {}
      |          ~~~~~~~~~~~~^~~~
/usr/include/c++/12.1.0/bits/stringfwd.h:72:11: note: declaration of ‘std::string’ {aka ‘class std::__cxx11::basic_string<char>’}
   72 |     class basic_string;
      |           ^~~~~~~~~~~~
/home/sysop/sc_source/src/extras/scrtdd/libs/hdd/solver.h: In constructor ‘HDD::Solver::Solver(std::string)’:
/home/sysop/sc_source/src/extras/scrtdd/libs/hdd/solver.h:123:40: error: use of deleted function ‘HDD::IdToIndex<std::__cxx11::basic_string<char> >::IdToIndex()’
  123 |   Solver(std::string type) : _type(type) {}
      |                                        ^
I
```

**Comment by morealaz** [comment]
I've done proposed changes and got no error, but some tests failed. Should I make a new issue or not?

**Comment by luca-s** [comment]
Thanks for the PR #65 . The failing tests cannot be related to your fixes. I will try then on my machine.

**Comment by morealaz** [comment]
For me `test_hdd_ttt` failed with a lot of errors like:

```
33: /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/ttt.cpp(178): error: in "test_ttt/_79": absolute value of diffAngle{-106.90000000000001} exceeds 15
33: Failure occurred in a following context:
33:     deltaIdx = 79; 
33: 
33: *** 30560 failures are detected in the test module "hdd"
33: 
```

and `test_hdd_dd` hangs with these messages being showed before hanging:

```
35: Test command: /home/sysop/sc_source/build/bin/test_hdd_dd
35: Environment variables: 
35:  SEISCOMP_ROOT=/home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data
35: Test timeout computed to be: 10000000
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.LQ will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.LR will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.Lg will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.PKP will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.PKPab will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.PKPbc will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.PKPdf will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.SKPdf will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.Rg will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.SKS will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.SS will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.ScS will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.pP_ will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.Pb will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.Sb will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.Is will not open!
35: 
35: File /home/sysop/sc_source/src/extras/scrtdd/libs/hdd/test/data/share/locsat/tables/iasp91.It will not open!
```

**Comment by luca-s** [comment]
Also, are you compiling seiscomp `master` or `v5` branch? `master` branch is never as stable as any release branch.

**Comment by morealaz** [comment]
I used `v5` branch and `test_hdd_ttt` and `test_hdd_dd` failed, but `test_hdd_dd` took `5548.45 sec` to complete.

**Comment by luca-s** [comment]
If `test_hdd_ttt` fails, it then makes sense that `test_hdd_dd` fails too, because the latter makes use of functionalities of the former. 

In `test_hdd_ttt` there are several travel time table tests: Seiscomp native (libtau and LOCSAT) and NonLinLoc grids. if we remove the nll grid files from the test data (`scrtdd/libs/hdd/test/data/nll/model`) the tests for the deleted grid files will be automatically skipped.

So I would like to ask you to remove the nll grid files, model by model and run `test_hdd_ttt` to see whether, at a certain point, the tests pass.

For example in your report I see that model `./data/nll/iasp91_2D_merc` is not working, I would start removing it:

`seiscomp/src/extras/scrtdd $ $ rm -f libs/hdd/test/data/nll/iasp91_2D_merc/{model,time}/*{hdr,buf}`

Then test:

`seiscomp/build $ ctest -R test_hdd_ttt`

I would then go on and remove another nll grid model and test until the tests pass (hopefully). I would try removing the nll model data in this order: `iasp91_2D_merc, iasp91_2D_lambert, iasp91_2D_azimuthal_equidist,  iasp91_2D_sdc, iasp91_2D_simple`. 

At the end you should be left with only seiscomp native models (libtau, LOCSAT) and hopefully the tests won't fail. If they still will, then the issue is somewhere else, but this testing would help me figure out where else to look for the bug.

Thanks!

**Comment by luca-s** [comment]
This is very suspicious. It looks like a random issue, which makes me think about memory issues with the code. Do you still have a version of the code where test_hdd_ttt fails? If so, would you be able to run:

 `BOOST_TEST_LOG_LEVEL=message ctest -R test_hdd_ttt -V`

and then report back the first error on the console, with some context (e.g. ~30 lines of log before the error)?

**Comment by luca-s** [comment]
@damb any chance you can try the test in my previous comment?

**Comment by damb** [comment]
I tried to reproduce the issue, as well.

First of all, I removed all the test data by means of the `clean.sh` script. Then I generated the test data for the models in the following order and ran the test:
- `iasp91_2D_merc` - passed
- `iasp91_2D_lambert` - passed
- `iasp91_2D_azimuthal_equidist` - passed
- `iasp91_2D_sdc` - passed
- `iasp91_2D_simple` - **failed** (output [out-01.txt](https://github.com/swiss-seismological-service/scrtdd/files/9282858/out-01.txt))

Next, I removed the test data from `iasp91_2D_simple` and rerun the tests. Although, I expected the tests to pass they **failed again** with the following output: [out-02.txt](https://github.com/swiss-seismological-service/scrtdd/files/9282868/out-02.txt).


I'm using `scrtdd` from `master` and `NonLinLoc v7.00.13 17Jan2022` (from https://github.com/alomax/NonLinLoc `master`) for generating the test data.

- OS: ArchLinux
- Compiler:

  ```bash
  $ gcc --version
  gcc (GCC) 12.1.0
  ```

I hope this helps.

**Comment by luca-s** [comment]
Thank you very much for your help @damb . The issue is [here](https://github.com/swiss-seismological-service/scrtdd/blob/4995205695020b2b16a9053d6a02faf4381e02cd/libs/hdd/test/ttt.cpp#L145) and [here](https://github.com/swiss-seismological-service/scrtdd/blob/4995205695020b2b16a9053d6a02faf4381e02cd/libs/hdd/test/ttt.cpp#L148). However `BOOST_CHECK_NO_THROW` hides the reason of the failure (the exception). Would you be able to remove the `BOOST_CHECK_NO_THROW` statement and keep the code inside it and run the test again?

**Comment by luca-s** [comment]
> Next, I removed the test data from iasp91_2D_simple and rerun the tests. Although, I expected the tests to pass they failed again with the following output: [out-02.txt](https://github.com/swiss-seismological-service/scrtdd/files/9282868/out-02.txt).

This is very suspicious. As I already mentioned in this thread if feels like a memory issue

**Comment by damb** [comment]
After removing the `BOOST_CHECK_NO_THROW` statement and recompiling I ran the same test, again:

- `iasp91_2D_merc` - **failed occasionally** ([out-03.txt](https://github.com/swiss-seismological-service/scrtdd/files/9284438/out-03.txt), [out-04.txt](https://github.com/swiss-seismological-service/scrtdd/files/9284481/out-04.txt), [out-05.txt](https://github.com/swiss-seismological-service/scrtdd/files/9284483/out-05.txt))

Now, I also checked the dumps. Particularly, the value of `yloc` is interesting. Most probably the issue is an uninitialized floating point variable.

**Comment by luca-s** [comment]
Thanks a lot for these logs @damb, I really appreciate your help. I agree with you the `yloc` is worth investigating, I noticed the same issue with @morealaz logs. In the meantime I ran valgrind on the code but I didn't find any memory issues, so I will investigate more and let you know.

**Comment by luca-s** [comment]
I pushed a commit that I believe it fixes the bug (usage of uninitialized variable in MERC transform). When you have time, would you be able to run the tests again @damb ? Thanks!

**Comment by damb** [comment]
fbf496a4238d9fe1fa1f7fb0716930a6e1efb28f seems to fix the issue. The tests pass successfully, now.

**Comment by luca-s** [comment]
Thanks a lot!
